rails_tut: "https://www.railstutorial.org/"
learnenough: "https://www.learnenough.com/"
rails_book: "https://railstutorial.org/book"
rubyonrails: "https://rubyonrails.org"
rails_help: "https://www/railstutorial.org/help"
rails_contact: "https://www/railstutorial.org/contact"
